version: '3.8'

services:
  grassmarlin:
    container_name: grassmarlin
    hostname: grassmarlin
    build: .
    #command: /usr/bin/grassmarlin # Agrega esta línea con el comando adecuado
    #command: /bin/sh
    ports:
      #- "8080:8080"
      - "2222:22"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/root/data
    environment:
      #- DISPLAY
      - XAUTHORITY=/tmp/.X11-unix/X0
      - WIRESHARK_EXEC=/usr/bin/wireshark
      - DISPLAY=${DISPLAY}
      - JAVA_TOOL_OPTIONS=-Dnio.mx=1024mb -Dnio.ms=512mb -Xms4096m -Xmx4096m  -XX:+UseG1GC -XX:+DisableExplicitGC -XX:NewSize=2048m -XX:MaxGCPauseMillis=2000 -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      - grassmarlin_network

networks:
  grassmarlin_network:
    driver: bridge
